"""New table Data

Revision ID: 1a0bfb47f4f8
Revises: 2e42d26617d4
Create Date: 2025-04-21 21:41:18.150776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0bfb47f4f8'
down_revision: Union[str, None] = '2e42d26617d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('temperature', sa.String(length=10), nullable=False),
        sa.Column('humidity', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('sensor_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_data_id'), 'sensor_data', ['id'], unique=False)
    op.add_column('sensors', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('sensors', sa.Column('data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensors', 'sensor_data', ['data_id'], ['id'], ondelete='SET NULL')
    op.execute("UPDATE sensors SET status = 'Ativo' WHERE status IS NULL")
    # Altera a coluna para NOT NULL
    op.alter_column('sensors', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.drop_column('sensors', 'data_id')
    op.drop_column('sensors', 'status')
    op.drop_index(op.f('ix_sensor_data_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    # ### end Alembic commands ###
