"""Remove data_id from sensors

Revision ID: 3dff10f027d3
Revises: 1a0bfb47f4f8
Create Date: 2025-04-23 21:46:11.168057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dff10f027d3'
down_revision: Union[str, None] = '1a0bfb47f4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'status')
    # ### end Alembic commands ###
